"""Evasion / targeted-misclassification attacks and the defense-aware adaptive
attack (kinematic mimicry of the spoofed benign class).
"""

from counterusv.attacks.marine_eot import (
    AXES,
    SEVERITY_LEVELS,
    MarineEOT,
    MarineEOTConfig,
    TransformParams,
    load_config,
)
from counterusv.attacks.patch import (
    PatchConfig,
    PatchCore,
    Placement,
    apply_patch_numpy,
    apply_patch_torch,
    filter_patch_eligible,
    is_patch_eligible,
    load_patch_config,
    non_printability_score,
    place_on_bbox,
    total_variation,
    xywh_to_xyxy,
)
from counterusv.attacks.evasion import (
    DifferentiableSurrogate,
    EvasionAttacker,
    EvasionConfig,
    EvasionInstanceResult,
    aggregate_esr,
    find_target_detection,
    iou_xyxy,
    load_evasion_config,
    make_evasion_loss,
    make_predict_fn,
    score_instance_esr,
    target_confidence,
    to_torch_device,
    to_ultralytics_device,
)
from counterusv.attacks.disguise import (
    DisguiseAttacker,
    DisguiseConfig,
    DisguiseInstanceResult,
    aggregate_tmsr,
    load_disguise_config,
    make_disguise_loss,
    score_instance_tmsr,
)

__all__ = [
    "AXES",
    "SEVERITY_LEVELS",
    "MarineEOT",
    "MarineEOTConfig",
    "TransformParams",
    "load_config",
    "PatchConfig",
    "PatchCore",
    "Placement",
    "apply_patch_numpy",
    "apply_patch_torch",
    "filter_patch_eligible",
    "is_patch_eligible",
    "load_patch_config",
    "non_printability_score",
    "place_on_bbox",
    "total_variation",
    "xywh_to_xyxy",
    "DifferentiableSurrogate",
    "EvasionAttacker",
    "EvasionConfig",
    "EvasionInstanceResult",
    "aggregate_esr",
    "find_target_detection",
    "iou_xyxy",
    "load_evasion_config",
    "make_evasion_loss",
    "make_predict_fn",
    "score_instance_esr",
    "target_confidence",
    "to_torch_device",
    "to_ultralytics_device",
    "DisguiseAttacker",
    "DisguiseConfig",
    "DisguiseInstanceResult",
    "aggregate_tmsr",
    "load_disguise_config",
    "make_disguise_loss",
    "score_instance_tmsr",
]
